name: reusable-example
on:
  workflow_call:
    secrets:
      message:
        description: a message to be show in logs
        required: true
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
    - name: log-message
      env:
        MESSAGE: ${{ secrets.MESSAGE }}
      shell: bash
      run: echo "the message is $MESSAGE"
